name: "Build Android app"

on:
    workflow_dispatch:

jobs:
    publish-apk:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache Android SDK
              uses: actions/cache@v3
              with:
                  path: /opt/android-studio
                  key: ${{ runner.os }}-android-studio

            - name: Install Android SDK
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install libc6:i386 libncurses6:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
                  wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
                  sudo mkdir -p /opt/android-studio/cmdline-tools/latest
                  sudo unzip -q commandlinetools-linux-11076708_latest.zip -d /opt/android-studio/cmdline-tools/latest
                  rm commandlinetools-linux-11076708_latest.zip
                  export PATH=$PATH:/opt/android-studio/cmdline-tools/latest/bin
                  yes | sdkmanager --licenses
                  yes | sdkmanager "platforms"
                  yes | sdkmanager "platform-tools"
                  yes | sdkmanager "build-tools"