name: "Build Android app"

on:
    push:
        branches:
            - main

jobs:
    publish-apk:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache Android SDK
              uses: actions/cache@v3
              with:
                  path: /opt/android-studio
                  key: ${{ runner.os }}-android-studio

            - name: Install Android SDK
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install libc6:i386 libncurses6:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386 google-android-cmdline-tools-9.0-installer
                  export JAVA_HOME=/opt/android-studio/jbr
                  echo y | sudo sdkmanager --install 'platforms' 'platform-tools' 'build-tools' 'ndk'
