name: "Build Windows app"

on:
    push:
        branches:
            - main

jobs:
    publish-tauri:
        permissions:
            contents: write
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Cache Cargo
              uses: actions/cache@v3
              with:
                  path: C:\Users\runneradmin\.cargo\registry
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Cache Tauri
              uses: actions/cache@v3
              with:
                  path: ./src-tauri/target
                  key: ${{ runner.os }}-tauri-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-tauri-

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: equation-calculator-v__VERSION__
                  releaseName: "Equation Calculator v__VERSION__"
                  releaseBody: "See the assets to download this version and install."

            - name: Get Version
              id: get_version
              run: |
                  echo "VERSION=$(cat src-tauri/Cargo.toml | grep version | cut -d '"' -f 2)" >> $GITHUB_ENV

            - name: Get Release Info
              id: get_release
              uses: actions/github-script@v6
              with:
                  script: |
                      const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
                      const release = await github.rest.repos.getReleaseByTag({
                          owner,
                          repo,
                          tag: `equation-calculator-v${process.env.VERSION}`,
                      });
                      return release.data.upload_url;
                  result-encoding: string

            - name: Upload release executable
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.get_release.outputs.result }}
                  asset_path: src-tauri/target/release/equation-calculator.exe
                  asset_name: equation-calculator-v${process.env.VERSION}.exe
                  asset_content_type: application/octet-stream
