name: 'Build Windows app'

on:
    push:
        branches: 
            - main

jobs:
    publish-tauri:
        permissions:
            contents: write
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: istall Rust stable
              uses: dtolnay/rust-toolchain@stable

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tagName: equation-calculator-v__VERSION__
                releaseName: 'Equation Calculator v__VERSION__'
                releaseBody: 'See the assets to download this version and install.'
                includeDebug: true
